Repository openshift-assisted/auto-report, pull requests merged in 2024-09, with the labels that each got.

#22 KONFLUX-1611: Add labels, licenses & user to Dockerfile
  .tekton/auto-report-saas-main-pull-request.yaml
  .tekton/auto-report-saas-main-push.yaml
  Dockerfile
Labels: approved, lgtm, size/S, jira/valid-reference

#34 NO-ISSUE: Fix konflux pipeline
  .tekton/auto-report-saas-main-pull-request.yaml
  .tekton/auto-report-saas-main-push.yaml
Labels: approved, lgtm, size/XS, jira/valid-reference

#32 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/auto-report-saas-main-pull-request.yaml
  .tekton/auto-report-saas-main-push.yaml
Labels: approved, lgtm, size/M, ok-to-test

#33 MGMT-18434: Upgrade setuptools to mitigate CVE-2024-6345
  requirements.txt
Labels: approved, lgtm, size/XS, jira/valid-reference
